// Code generated by MockGen. DO NOT EDIT.
// Source: internal/reader/client/flight.go
//
// Generated by this command:
//
//	mockgen -source internal/reader/client/flight.go -destination=internal/test/mock/mock_flight_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/ansoncht/flight-microservices/internal/reader/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFlight is a mock of Flight interface.
type MockFlight struct {
	ctrl     *gomock.Controller
	recorder *MockFlightMockRecorder
	isgomock struct{}
}

// MockFlightMockRecorder is the mock recorder for MockFlight.
type MockFlightMockRecorder struct {
	mock *MockFlight
}

// NewMockFlight creates a new mock instance.
func NewMockFlight(ctrl *gomock.Controller) *MockFlight {
	mock := &MockFlight{ctrl: ctrl}
	mock.recorder = &MockFlightMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlight) EXPECT() *MockFlightMockRecorder {
	return m.recorder
}

// FetchFlights mocks base method.
func (m *MockFlight) FetchFlights(ctx context.Context, airportCode, start, end string) ([]model.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFlights", ctx, airportCode, start, end)
	ret0, _ := ret[0].([]model.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFlights indicates an expected call of FetchFlights.
func (mr *MockFlightMockRecorder) FetchFlights(ctx, airportCode, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFlights", reflect.TypeOf((*MockFlight)(nil).FetchFlights), ctx, airportCode, start, end)
}
