http-server:
  port: 9099
  timeout: 10
http-client:
  timeout: 10
grpc-client:
  address: localhost:9098
flight-fetcher:
  url: ''
  user: ''
  pass: ''
route-fetcher:
  url: ''
scheduler:
  airports: 'VHHH'
logger:
  json: true
  level: 'info'
