http_server:
  port: 8080
  timeout: 75
http_client:
  timeout: 70
flight_api:
  url: ''
  user: ''
  pass: ''
route_api:
  url: ''
kafka_writer:
  address: ''
  topic: ''
logger:
  json: true
  level: 'info'
