// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.27.1
// source: summarizer.proto

package summarizer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flight      string `protobuf:"bytes,1,opt,name=flight,proto3" json:"flight,omitempty"`
	Origin      string `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *PullFlightRequest) Reset() {
	*x = PullFlightRequest{}
	mi := &file_summarizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFlightRequest) ProtoMessage() {}

func (x *PullFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_summarizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFlightRequest.ProtoReflect.Descriptor instead.
func (*PullFlightRequest) Descriptor() ([]byte, []int) {
	return file_summarizer_proto_rawDescGZIP(), []int{0}
}

func (x *PullFlightRequest) GetFlight() string {
	if x != nil {
		return x.Flight
	}
	return ""
}

func (x *PullFlightRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *PullFlightRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type PullFlightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PullFlightResponse) Reset() {
	*x = PullFlightResponse{}
	mi := &file_summarizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullFlightResponse) ProtoMessage() {}

func (x *PullFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_summarizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullFlightResponse.ProtoReflect.Descriptor instead.
func (*PullFlightResponse) Descriptor() ([]byte, []int) {
	return file_summarizer_proto_rawDescGZIP(), []int{1}
}

var File_summarizer_proto protoreflect.FileDescriptor

var file_summarizer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x22, 0x65, 0x0a, 0x11, 0x50, 0x75,
	0x6c, 0x6c, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x75, 0x6c, 0x6c, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x55, 0x0a, 0x0a, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x0a, 0x50, 0x75, 0x6c, 0x6c, 0x46, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x19, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x50, 0x75, 0x6c,
	0x6c, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x3b,
	0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x73,
	0x6f, 0x6e, 0x63, 0x68, 0x74, 0x2f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2d, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_summarizer_proto_rawDescOnce sync.Once
	file_summarizer_proto_rawDescData = file_summarizer_proto_rawDesc
)

func file_summarizer_proto_rawDescGZIP() []byte {
	file_summarizer_proto_rawDescOnce.Do(func() {
		file_summarizer_proto_rawDescData = protoimpl.X.CompressGZIP(file_summarizer_proto_rawDescData)
	})
	return file_summarizer_proto_rawDescData
}

var file_summarizer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_summarizer_proto_goTypes = []any{
	(*PullFlightRequest)(nil),  // 0: flight.PullFlightRequest
	(*PullFlightResponse)(nil), // 1: flight.PullFlightResponse
}
var file_summarizer_proto_depIdxs = []int32{
	0, // 0: flight.Summarizer.PullFlight:input_type -> flight.PullFlightRequest
	1, // 1: flight.Summarizer.PullFlight:output_type -> flight.PullFlightResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_summarizer_proto_init() }
func file_summarizer_proto_init() {
	if File_summarizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_summarizer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_summarizer_proto_goTypes,
		DependencyIndexes: file_summarizer_proto_depIdxs,
		MessageInfos:      file_summarizer_proto_msgTypes,
	}.Build()
	File_summarizer_proto = out.File
	file_summarizer_proto_rawDesc = nil
	file_summarizer_proto_goTypes = nil
	file_summarizer_proto_depIdxs = nil
}
