// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: summarizer.proto

package summarizer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Summarizer_PullFlight_FullMethodName = "/flight.Summarizer/PullFlight"
)

// SummarizerClient is the client API for Summarizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SummarizerClient interface {
	PullFlight(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PullFlightRequest, PullFlightResponse], error)
}

type summarizerClient struct {
	cc grpc.ClientConnInterface
}

func NewSummarizerClient(cc grpc.ClientConnInterface) SummarizerClient {
	return &summarizerClient{cc}
}

func (c *summarizerClient) PullFlight(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PullFlightRequest, PullFlightResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Summarizer_ServiceDesc.Streams[0], Summarizer_PullFlight_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullFlightRequest, PullFlightResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Summarizer_PullFlightClient = grpc.ClientStreamingClient[PullFlightRequest, PullFlightResponse]

// SummarizerServer is the server API for Summarizer service.
// All implementations must embed UnimplementedSummarizerServer
// for forward compatibility.
type SummarizerServer interface {
	PullFlight(grpc.ClientStreamingServer[PullFlightRequest, PullFlightResponse]) error
	mustEmbedUnimplementedSummarizerServer()
}

// UnimplementedSummarizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSummarizerServer struct{}

func (UnimplementedSummarizerServer) PullFlight(grpc.ClientStreamingServer[PullFlightRequest, PullFlightResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PullFlight not implemented")
}
func (UnimplementedSummarizerServer) mustEmbedUnimplementedSummarizerServer() {}
func (UnimplementedSummarizerServer) testEmbeddedByValue()                    {}

// UnsafeSummarizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SummarizerServer will
// result in compilation errors.
type UnsafeSummarizerServer interface {
	mustEmbedUnimplementedSummarizerServer()
}

func RegisterSummarizerServer(s grpc.ServiceRegistrar, srv SummarizerServer) {
	// If the following call pancis, it indicates UnimplementedSummarizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Summarizer_ServiceDesc, srv)
}

func _Summarizer_PullFlight_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SummarizerServer).PullFlight(&grpc.GenericServerStream[PullFlightRequest, PullFlightResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Summarizer_PullFlightServer = grpc.ClientStreamingServer[PullFlightRequest, PullFlightResponse]

// Summarizer_ServiceDesc is the grpc.ServiceDesc for Summarizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Summarizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flight.Summarizer",
	HandlerType: (*SummarizerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullFlight",
			Handler:       _Summarizer_PullFlight_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "summarizer.proto",
}
