// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: summarizer.proto

package summarizer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Summarizer_PullFlight_FullMethodName = "/tutorial.Summarizer/PullFlight"
)

// SummarizerClient is the client API for Summarizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SummarizerClient interface {
	PullFlight(ctx context.Context, in *PullFlightRequest, opts ...grpc.CallOption) (*PullFlightResponse, error)
}

type summarizerClient struct {
	cc grpc.ClientConnInterface
}

func NewSummarizerClient(cc grpc.ClientConnInterface) SummarizerClient {
	return &summarizerClient{cc}
}

func (c *summarizerClient) PullFlight(ctx context.Context, in *PullFlightRequest, opts ...grpc.CallOption) (*PullFlightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullFlightResponse)
	err := c.cc.Invoke(ctx, Summarizer_PullFlight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummarizerServer is the server API for Summarizer service.
// All implementations must embed UnimplementedSummarizerServer
// for forward compatibility.
type SummarizerServer interface {
	PullFlight(context.Context, *PullFlightRequest) (*PullFlightResponse, error)
	mustEmbedUnimplementedSummarizerServer()
}

// UnimplementedSummarizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSummarizerServer struct{}

func (UnimplementedSummarizerServer) PullFlight(context.Context, *PullFlightRequest) (*PullFlightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullFlight not implemented")
}
func (UnimplementedSummarizerServer) mustEmbedUnimplementedSummarizerServer() {}
func (UnimplementedSummarizerServer) testEmbeddedByValue()                    {}

// UnsafeSummarizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SummarizerServer will
// result in compilation errors.
type UnsafeSummarizerServer interface {
	mustEmbedUnimplementedSummarizerServer()
}

func RegisterSummarizerServer(s grpc.ServiceRegistrar, srv SummarizerServer) {
	// If the following call pancis, it indicates UnimplementedSummarizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Summarizer_ServiceDesc, srv)
}

func _Summarizer_PullFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummarizerServer).PullFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Summarizer_PullFlight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummarizerServer).PullFlight(ctx, req.(*PullFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Summarizer_ServiceDesc is the grpc.ServiceDesc for Summarizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Summarizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tutorial.Summarizer",
	HandlerType: (*SummarizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullFlight",
			Handler:    _Summarizer_PullFlight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "summarizer.proto",
}
