grpc-server:
  port: 9097
http-client:
  timeout: 10
threads:
  url: https://graph.threads.net
  access-token: ''
twitter:
  access-token-key: ''
  access-token-secret: ''
logger:
  json: true
  level: 'info'
